version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - weather
    volumes:
      - .:/app
      - ./data:/data

  weather:
    build:
      context: ./weather_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

volumes:
  sqlite_data: 
